/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./layouts/AuthLayout.vue')['default']
    CheckboxInput: typeof import('./components/common/forms/checkboxInput.vue')['default']
    DefaultLayout: typeof import('./layouts/DefaultLayout.vue')['default']
    FileUploadInput: typeof import('./components/common/forms/FileUploadInput.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    PriceInput: typeof import('./components/common/forms/PriceInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectInput: typeof import('./components/common/forms/selectInput.vue')['default']
    SelectWithIconInput: typeof import('./components/common/forms/SelectWithIconInput.vue')['default']
    TextareaInput: typeof import('./components/common/forms/TextareaInput.vue')['default']
    TextInput: typeof import('./components/common/forms/textInput.vue')['default']
  }
}
