/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDialog: typeof import('./components/common/AppDialog.vue')['default']
    AuthLayout: typeof import('./layouts/AuthLayout.vue')['default']
    ButtonWithIcon: typeof import('./components/common/buttons/ButtonWithIcon.vue')['default']
    CheckboxInput: typeof import('./components/common/forms/checkboxInput.vue')['default']
    ColorPickerInput: typeof import('./components/common/forms/ColorPickerInput.vue')['default']
    DataTable: typeof import('./components/common/tables/DataTable.vue')['default']
    DatePickerInput: typeof import('./components/common/forms/DatePickerInput.vue')['default']
    DefaultLayout: typeof import('./layouts/DefaultLayout.vue')['default']
    DeleteConfirmDialog: typeof import('./components/common/DeleteConfirmDialog.vue')['default']
    EditableDataTable: typeof import('./components/common/tables/EditableDataTable.vue')['default']
    FileUploadInput: typeof import('./components/common/forms/FileUploadInput.vue')['default']
    GroupedDataTable: typeof import('./components/common/tables/GroupedDataTable.vue')['default']
    LanguageTabs: typeof import('./components/common/forms/LanguageTabs.vue')['default']
    Map: typeof import('./components/common/Map.vue')['default']
    MapDialog: typeof import('./components/common/MapDialog.vue')['default']
    MultipleSelectInput: typeof import('./components/common/forms/MultipleSelectInput.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    PriceInput: typeof import('./components/common/forms/PriceInput.vue')['default']
    RichTextEditor: typeof import('./components/common/forms/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaudiPhoneInput: typeof import('./components/common/forms/SaudiPhoneInput.vue')['default']
    SelectInput: typeof import('./components/common/forms/selectInput.vue')['default']
    SelectWithIconInput: typeof import('./components/common/forms/SelectWithIconInput.vue')['default']
    StatusChangeDialog: typeof import('./components/common/StatusChangeDialog.vue')['default']
    TelInput: typeof import('./components/common/forms/TelInput.vue')['default']
    TextareaInput: typeof import('./components/common/forms/TextareaInput.vue')['default']
    TextInput: typeof import('./components/common/forms/textInput.vue')['default']
  }
}
